version: "2"
distribution_spec:
  description: Agents distribution for the AI Masterclass 2025
  providers:
    inference:
      - provider_type: remote::ollama
    telemetry:
      - provider_type: inline::meta-reference
    agents:
      - provider_type: inline::meta-reference
    tool_runtime:
      - provider_type: remote::brave-search
      - provider_type: remote::tavily-search
      - provider_type: inline::rag-runtime
      - provider_type: remote::model-context-protocol
    safety:
      - provider_type: inline::llama-guard
    vector_io:
      - provider_type: inline::milvus
image_type: venv
image_name: masterclass_agents
additional_pip_packages:
- sqlalchemy[asyncio]
- geocoder